### ISSUE TITLE
Moving to Dynamic Polymorphism: Calling Overridden Functions from the Constructor

### ISSUE THREAD

**Issue by samasri** [eclipse/omr#3235] opened 2018-11-23 23:58 UTC
# Motivation
As part of the Centre of Academic studies, a research group (myself, @snadi , @rwy0717 , @xliang6 , @nbhuiyan , @mgaudet ) is working on changing the variability implementation in OMR to use dynamic polymorphism instead of static polymorphism. We have already virtualized the overridden functions in some class hierarchies and created PRs for them (our PRs so far include: [CodeGenerator](https://github.com/eclipse/omr/pull/2639), [MemoryReference](https://github.com/eclipse/omr/pull/3162), and [Symbol](https://github.com/eclipse/omr/pull/3215)).

Consequences of static polymorphism can be found in an [issue](https://github.com/eclipse/omr/issues/1797) opened earlier by [mgaudet](https://github.com/mgaudet) as well as in our previous [proposal](https://github.com/eclipse/omr/issues/2583) discussed in the [OMR Compiler Architecture Meeting](https://github.com/eclipse/omr/issues/2571). Please note that our proposal has slightly changed since the OMR Compiler Architecture Meeting; it was decided to change the proposal to moving completely to dynamic polymorphism (virtualize all overridden functions), instead of hybrid polymorphism, as was described in the [proposal](https://github.com/eclipse/omr/issues/2583).

# Challenge Faced
While virtualizing all overridden functions of the `CodeGenerator` class hierarchy, we realized that there are two overridden functions that are being called from the constructor: `OMR::CodeGenerator::createLinkage(TR_LinkageConventions lc)` and `OMR::CodeGenerator::createLinkageForCompilation()`. After virtualizing those functions, calling them from the constructor would not result in their most specific implementation to be triggered as explained in [this isocpp FAQ](https://isocpp.org/wiki/faq/strange-inheritance#calling-virtuals-from-ctors).

# Proposed Solution
In order to solve this, we propose and apply in our [CodeGenerator PR](https://github.com/eclipse/omr/pull/2639) the following solution:
1. Move all the code of the `CodeGenerator` constructor, from the point of calling any of the virtual functions (`createLinkage` or `createLinkageForCompilation`) to another function called `initializeConstruction`.
2. Call `initializeConstruction()` after every `CodeGenerator` constructor call. Since the OMR project only calls the `CodeGenerator` constructor once, [here](https://github.com/eclipse/omr/blob/master/compiler/compile/OMRCompilation.cpp#L189), we only had to add a call for `initializeConstruction` after that line.

@dsouzai, @fjeremic, @dibyendumajumdar, @0xdaryl: since you've commented or reacted to previous discussions about this, you might be interested in our proposed solution. We would appreciate your comments on it.

**Comment by dibyendumajumdar** [comment] 2018-11-24 21:30
Hi, sorry I haven't looked at the code, so my comments are general ones. Presumably the problem is that a derived typed of CodeGenerator is being constructed? Is it possible to do the initialization  in the derived constructor? I personally dislike the idea of performing initialization post construction.

**Comment by mgaudet** [comment] 2018-11-24 21:32
I think this is an interesting notion; perhaps the general plan should be to transition to factory functions to allow this sort of two phase initialization?

**Comment by dibyendumajumdar** [comment] 2018-11-24 21:34
Yes, as is done in Java apps, the implementation should be wired in somehow, maybe via configuration. Harder to do in C++ of course.

**Comment by samasri** [comment] 2018-11-25 01:13
@dibyendumajumdar The problem is not that a constructor of a derived type is being called, it is the fact that the constructor of the derived type is calling virtual functions that are implemented in that same derived type. When a derived class's constructor calls a virtual function that is implemented in both, the base and derived classes. The call, in that case, is not resolved to the implementation in the derived class, instead, it is resolved to the implementation in the base class, because the function is virtual. This virtual function (and all the code related to it) is extracted to the `initializeConstruction` function that is then called after the constructor.

I agree that post construction has consequences, and thanks for pointing that out. As @mgaudet mentioned, it is a good idea in this case to transition to factory functions that allow such two phased initialization. However, it appears to me that `CodeGenerator` already has that factory function and this factory function ([`allocateCodeGenerator`](https://github.com/samasri/omr/blob/Virtualizing-CodeGenerator/compiler/compile/OMRCompilation.cpp#L187-L192)). And this is where we added our `initializeConstruction` call.

**Comment by 0xdaryl** [comment] 2020-09-21 12:23
I am in the process of adapting the CodeGenerator hierarchy construction to use a factory pattern.  It will arrive in a series of staged PRs as there is work needed in consuming downstream projects to keep up with the changes.  The goal of this initial work will be to simply replicate the functionality that is there but follow a factory allocation pattern that separates construction from initialization.  Feedback on the PRs is certainly welcome.

In studying the initialization code there is obviously more work that could be done to streamline and logically order the initialization events, but that is not the subject of this work.

**Comment by 0xdaryl** [comment] 2020-11-05 17:55
With the merging of #5647 the CodeGenerator has moved to a factory construction pattern.  The constructors simply perform member initialization now with the original initialization logic moved to a separate `initialize()` function.  Closing this issue now.

**Closed by 0xdaryl** 2020-11-05 17:55 UTC
Labels: comp:compiler, discussion
