### ISSUE TITLE
Using Port in Compiler

### ISSUE THREAD

**Issue by noryb009** [eclipse/omr#589] opened 2016-12-08 16:06 UTC
Ideally, the port library should be used within the compiler to increase portability and remove some platform-specific `#ifdef`s.

Unfortunately, there are two issues with this:
1. This adds another dependency to anything that uses the compiler component. This may add a bit of resistance to adoption.
2. The port library requires the thread library during initialization and to perform some operations. The thread library must be initialized by the downstream project.

I personally believe the first is a fair trade-off, trading another dependency for ease of development. However, the second issue is more concerning, since as far as I can tell, the downstream needs to make some (perhaps major) changes to how it handles OS threads. This brings up a few questions:

1. How much effort is required to make the thread library an optional dependency of the port library?
2. Can the thread library be lazily initialized in each thread in the compiler? A followup question would be how it could be uninitialized in each thread, which might be harder.
3. Is there some other way for us to remove the burden of explicitly using the thread library from downstream projects that just want the compiler component?

**Comment by dibyendumajumdar** [comment] 2016-12-10 20:59
Hi, what will be the compiler gain by using port? I assume by definition the compiler is not portable across platforms. I think that if today it is standalone then it is better to keep it that way. In any case, is it just that code will look nicer or are there real gains?

I speak as someone interested in using the JIT compiler.

Regards

**Comment by Leonardo2718** [comment] 2016-12-10 21:36
Hi @dibyendumajumdar 

Not sure if I'm the most qualified person to answer your question but I'll give it a try.

The OMR compiler actually is portable across platforms. A lot of the technology (e.g. the optimizer) is platform independent. Only a few components, the code generator in particular, are platform specific.

If you look in the `compiler/` directory, you will find the `x/`, `p/`, and `z/` sub-directories. These contain the compiler code specific to the x86 (32 and 64 bit), Power (PowerPC), and IBM z Systems architectures respectively. The build system has mechanisms for selecting the appropriate directory depending on the build platform.

The main benefit of using the port library is that it provides a more formal/consistent API for asking questions about the environment. Using it would make the compiler code more consistent with the other components and making integration easier.

The point of this issue is to have a discussion about the trade-offs of using the port library in the compiler, so thanks for contributing and sharing your thoughts!

Hope that helps!

**Comment by dibyendumajumdar** [comment] 2016-12-10 21:55
Hi @Leonardo2718 

> The main benefit of using the port library is that it provides a more formal/consistent API for asking questions about the environment. Using it would make the compiler code more consistent with the other components and making integration easier.

If I am reading you correctly above, it seems that there is no immediate real benefit to using the port. That is, nothing is broken that needs fixing. Re integration it goes the other way too - for consumers of JIT technology, the standalone nature is more attractive.

I am being selfish here - I would like to use the JIT technology, and not have other things pulled in. I may have my own notion of a port library (I use libuv for instance). 

Regards

**Comment by charliegracie** [comment] 2016-12-12 16:34
The Port and Thread libraries provide an OS / Architecture agnostic API that should *IMO* be used by all OMR components.  They should be considered the basic building blocks of OMR and the minimum set of features that OMR provides. The reason for using them is so that each component can write their code once and have it work on all OS / architectures that are supported by OMR.

**Comment by noryb009** [comment] 2016-12-13 22:01
> there is no immediate real benefit to using the port

The benefit is that future development can be completed quicker and by a wider audience. Abstracting away these system differences allows developers to use a single consistent system interface. Putting them into a library is a logical next step to allow the work to be used by other projects. A wider range of developers can work on the compiler (for example) because of hardware differences being abstracted away - I don't expect many developers to have access to an AIX or z/OS machine to test on.

> I may have my own notion of a port library

Note that the compiler using the port component does not necessarily mean you need to use the port component.

> the standalone nature is more attractive

I realize this, but the question remains how much more attractive it is. That's why I created this issue: to find out how much extra work is required by downstream projects if the JIT was not standalone. I believe adding a single library to a link path is not a great barrier, however making major changes to your code is. Understanding this barrier allows us to understand how much more attractive this standalone nature really is, thus letting us make an informed decision.


@charliegracie It may add another barrier for users wanting to try the JIT, without pulling in the rest of OMR (like @dibyendumajumdar mentioned). Every extra line required or library linked adds a little bit of resistance. If `OMR_Initialize_VM` actually sets up everything that is needed, you are correct that this would not add much of a barrier. However, would each thread still need to call `omrthread_attach_ex` before using any OMR component?

**Comment by dibyendumajumdar** [comment] 2016-12-14 00:34
Hi, I guess I am in a minority here, but anyway here are my thoughts. I have built a JIT compiler implementation for Lua, using LLVM. The thing about Lua is that 'less is more'. LLVM is a huge beast, so it makes the JIT technology unviable in the domains where Lua is used. There is always LuaJIT to remind us how much small the JIT compiler for Lua needs to be. I have been looking for an alternative to LLVM that has a smaller footprint and was designed for JIT compilation (LLVM wasn't really designed for that), hence my interest in OMR. But I am getting the impression that the OMR JIT technology is being seen as one component of OMR and not a separate thing. And as part of the OMR toolkit integration with OMR components makes sense. But perhaps OMR is not the right technology for Lua, after all.

**Comment by mstoodle** [comment] 2016-12-14 03:16
Hi @dibyendumajumdar , how small are we talking about here? While the OMR JIT is *probably* smaller than an LLVM based compiler, from the way you're talking I'm not actually sure it's even in the right ballpark so it would be nice to know what kind of footprint target you're talking about. How small does it "need" to be?

My opinion, which might have a slightly different flavour than Charlie's, is that the components should integrate well together, but that shouldn't mean they *must* be integrated.

Personally, I think there's some good value offered by the port/thread library over and above just the "common" platform interface they provide to the OMR components and the points @noryb009 mentioned when he opened this issue. We haven't talked about this value much. For example, routing all memory allocation through the port library enables memory allocation tracking which makes it much easier to understand and target runtime-wide memory footprint improvements. Another example: having mutexes all coming from the same library brings diagnostic and introspection abilities you wouldn't otherwise have (threads waiting on a mutex, show the state of all monitors, etc.). By leveraging the OMR port/thread library, the JIT gets access to these things along with all other components. In the IBM J9 JVM, the JIT uses only the port and thread libraries, with the benefits that JIT memory, thread, mutex, and other diagnostics can all be very easily shown in our javacore files and can be very easily examined in core files using our diagnostic extensions (DDR and other). And it's not just introspection for when problems happen, the same underlying facilities enable online monitoring and management of the runtime behaviour.

But I suppose that these facilities may not be interesting or useful for all runtimes, which motivates the somewhat dual position expressed in the second paragraph.

**Comment by mstoodle** [comment] 2016-12-14 03:19
By the way, thanks for participating in this discussion, @dibyendumajumdar ! While you might feel yourself in the minority, we are certainly interested to hear about your thoughts and want to understand the reasoning behind your position.

**Comment by dibyendumajumdar** [comment] 2016-12-14 09:39
Hi @mstoodle 

Re size on 64-bit Linux, the LLVM version (of my project) builds to roughly 20MB binary in size. I saw that OMR JIT test binaries are about 7MB so that could mean a significant reduction for my project. I built OMR using the default instructions so not sure whether these builds have debug information turned on - which might affect the build size.

LuaJIT is of course about 500k in size. Even if this level of compactness can't be achieved, 7MB versus 20MB looks good, but ideally smaller the better.

In an ideal world (if I could make a wish), I would have liked the OMR project to be broken up into separate top level projects, with port, thread, compiler separate top level projects, and similarly other components.

**Comment by dibyendumajumdar** [comment] 2016-12-14 09:46
Sorry last post on this topic - I guess I am saying please please make the JIT compiler as independent and standalone as possible from rest of OMR and please please make it as compact / lean as possible!

**Comment by mstoodle** [comment] 2016-12-14 15:01
Thanks for the information @dibyendumajumdar . I wanted to see where we stood and you've provided some great context for us going forward. From what you've provided, it seems like we're at fairly decent "middle" right now, and I don't really see that making port and thread part of the pre-requisites for the JIT would substantially change the trade-off point we're at in terms of footprint.

I believe port + thread in their entirety should be around 1 MB -1.5 MB (on 64-bit x86 Linux), and we can hopefully find ways to trim that number for those scenarios that only use the JIT component. I think we'll probably continue down the path towards optimizing our integration, because there are important benefits to be had down that path.

But we'll certainly keep the footprint point in mind, as Lua isn't the only language with this kind of concern with footprint. Many of us come from the IBM J9 JVM development team, where we have spent considerable effort battling footprint concerns over the years. Footprint is also a key metric for cloud-based workloads. As a community, we need to care about this issue.

Thanks again for contributing to this issue!

**Comment by Leonardo2718** [comment] 2016-12-14 15:29
As a Lua developer myself, I understand the desire for a small footprint. I think it's important that the OMR compiler try to be as small as possible.

That said I also understand the long-term benefit of using the port library.

I think that in it's current state, the compiler technology has an acceptable footprint. There is definitely room for improvement though. Some changes that increase the footprint are acceptable, as long as they provide enough value to the project and we try to keep the increase as small as possible.

For reference, a production build of [Lua Vermelha](https://github.com/Leonardo2718/lua-vermelha), which I'm currently developing, is roughly 8MB. With a bit of optimization work, I think this can be reduced.

**Comment by dibyendumajumdar** [comment] 2016-12-18 23:33
Hi @Leonardo2718,

Great that you are implementing a JIT for Lua using OMR. It will save me a lot of effort as I will be able to see the results from your implementation before embarking on using OMR in my project.

Regards

**Comment by mstoodle** [comment] 2016-12-22 17:15
Lest my earlier comment leave anyone thinking I am not completely in favour of using port and thread in the JIT compiler, let me state it clearly: IMO, we should leverage port and thread in the compiler component.

The alternative is to have our own versions of the code we need from port and thread, which doesn't make any sense either.

The other stuff I said about needing to pay attention to footprint and other scenarios was meant to convey that this position was not ignoring those concerns or that those concerns are not important: it is a judgement and priority call for the compiler component, and I feel using port/thread is the better decision. I'll try to be more clear about that kind of thing in the future.

I am going to close this issue now, as I believe we have resolved our direction. If there are unanswered questions that need answering, please open new issues.

**Closed by mstoodle** 2016-12-22 17:15 UTC
