### ISSUE TITLE
Document proper use of the TR:: namespace

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#2084] opened 2017-11-30 05:04 UTC
Provide documentation (under `doc/compiler`) describing the expected use cases for the `TR::` namespace in the context of extensible classes and in a more general compiler context.

**Comment by mgaudet** [comment] 2017-11-30 13:57
[This is currently in doc/compiler/Extensible_Classes_in_OMR.md](https://github.com/eclipse/omr/blob/master/doc/compiler/extensible_classes/Extensible_Classes_in_OMR.md)

> We use the TR:: namespace to serve this purpose. Outside of the layered construction of an extensible class, all compiler code uses the TR:: namespace (rooted in the code name for the compiler technology which was Testasrossa).
> 
> In the case of extensible classes, we expose them to consumers by providing a terminating subclass in the TR:: namespace, which we call the Concrete class.
> 
> In the case of classes that aren't extensible, It is perfectly legitimate to create a class directly in the TR:: namespace if it's complete and can and should be used as-is.

Not sufficient?

**Comment by mgaudet** [comment] 2017-11-30 13:58
(This feels like a dupe of #788)

**Comment by 0xdaryl** [comment] 2017-12-04 21:31
@mgaudet:  yes, the discussion that preceded those updates to the Extensible Class documentation slipped my mind.  I think I want to surface that text somewhere other than the Extensible Classes documentation though as the `TR::` namespace has uses beyond it.  I'll keep this issue open in the meantime.

**Closed** 2019-01-28 21:20 UTC
Labels: backlog, compiler, documentation
