### ISSUE TITLE
JVM fails to start when /proc is mounted with the option hidepid=2

### ISSUE THREAD

**Issue by paulcheeseman** [eclipse/omr#7021] opened 2023-06-05 15:17 UTC
The cgroup v1 container detection code in `/port/unix/omrsysinfo.c` requires that `/proc/1/cgroup` is accessible. If `/proc` is mounted with the option `hidepid=2`, a regular user without root privileges will not be able to access this pseudo-file, and a JVM launched by that user will fail to start with the following error:

```
Error: Port Library failed to initialize: -89
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

However, this is only the case after this patch (specifically, lines 3609-3611 in `omrsysinfo.c`):

https://github.ibm.com/runtimes/openj9-omr/commit/ec766dee69a6089a6242746a2424c3c7e8948938

Prior to this change, the failure to read `/proc/1/cgroup` in `isRunningInContainer()` was effectively swallowed and the JVM started up regardless. After the change, this scenario is treated as a fatal error and the JVM fails to start.

So the main question here is:  is the new behaviour correct, or was the old behaviour more desirable?

On the one hand the new behaviour can be seen as a "regression" by users, but it seems to me that there is a danger associated with the old behaviour, by continuing after a failure to read `/proc/1/cgroup` and assuming that the JVM is _not_ running in a container. It's possible that it _is_ in fact running in a container, in which case the JVM would fail to adapt to the container's limitations and consume an undesirable amount of resources. Perhaps continuing with a warning would be a sensible compromise?

Reproduction instructions:
1. `sudo mount -o remount,rw,hidepid=2 /proc`
2. `java -version`

I tested with IBM Java 8.0.7.11 (shows the old behaviour) and IBM Java 8.0.7.15 (shows the new behaviour).

There are a couple of other less significant issues here:

1. The error message is completely opaque to the user, who has no way to know what the error code `-89` means. It's not documented anywhere, and it wasn't trivial to determine what it meant even with access to the source code.
2. The tracepoints in the container detection code in `omrsysinfo.c` never fire because the code is executed before the Xtrace engine is initialized.

**Comment by babsingh** [comment] 2023-06-08 20:01
@paulcheeseman https://github.com/eclipse-openj9/openj9/pull/17560 and https://github.com/eclipse/omr/pull/7029 have been opened to address this issue. Currently, running a personal build: https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/16914. Actually, I am unable to reproduce the failure locally on Ubuntu using the instructions in https://github.com/eclipse/omr/issues/7021#issue-1742008426. Can you help verify if the solution works on your end?

**Comment by babsingh** [comment] 2023-06-15 15:11
Closing: The solution, https://github.com/eclipse-openj9/openj9/pull/17560 and https://github.com/eclipse/omr/pull/7029, has been merged.

**Closed by babsingh** 2023-06-15 15:11 UTC
