### ISSUE TITLE
TR_OutlinedInstructionsGenerator destructor allocates memory and crashes

### ISSUE THREAD

**Issue by JamesKingdon** [eclipse/omr#4846] opened 2020-02-19 15:53 UTC
This is a continuation of issue #3083 in which the destructor caused crashes by throwing during the unwind of a previous throw. The fix for that issue missed the case where the first allocation failure is from the destructor itself. This also causes the application to terminate abruptly.

**Comment by fjeremic** [comment] 2020-02-19 16:38
@JamesKingdon is this something specific to x86 or is it cross platform?

**Comment by JamesKingdon** [comment] 2020-02-19 18:49
That's unknown. The basic issue will be cross platform, but I'm told the precise behaviour may depend on the specific compiler used to build the executable.

**Comment by aviansie-ben** [comment] 2020-02-19 20:38
I can clarify here since I was present when this was being discussed internally. This particular issue is specific to the destructor for `TR_OutlinedInstructionsGenerator`, which is defined in the x codegen: https://github.com/eclipse/omr/blob/6d76bf2b1af793eba5b0a0dfa19428cb30792c8a/compiler/x/codegen/OutlinedInstructions.cpp#L382-L389

Similar problematic destructors may be present elsewhere and could affect other platforms, but a thorough search for other potential instances of this has not yet been performed AFAIK so this is the only known problematic destructor for now.

**Comment by JamesKingdon** [comment] 2020-02-19 20:45
Ah, thanks Ben. I forgot it was in the X specific codegen :)

**Comment by Leonardo2718** [comment] 2020-02-19 22:16
To elaborate, the problem is in the call to `generateLabelInstruction()` because it must perform an allocation. If the allocation fails, an exception will be thrown.

Since C++11, class destructors are considered `noexcept`, or non-throwing, by default. `noexcept` causes `std::terminate()` to be called if an exception ever reaches the outer most block of the function, or destructor in this case, without being caught.

The problem we observed is that if `generateLabelInstruction()` throws an exception because a memory allocation fails (or for any other reason really), the compilation will not abort as expected and the whole program terminates. Incidentally, the handler triggered by the termination also attempts and fails to do an allocation in order to generate a jitdump, resulting in a second call to `std::terminate()` (this time because an uncaught exception already exists) that takes down the program.

A subtlety of this problem is that it only exists if the JIT is built with a compiler that implements default `noexcept` destructors, which I don't believe all our build compilers do.

**Comment by andrewcraik** [comment] 2020-03-18 13:42
@Leonardo2718 as a tactical fix would it make sense to declare the destructor as noexcept(false) for now so that we would get the behaviour we have been used to and can look at a more broad design reconsideration with less time pressure. eg fix the functional problem and then fix the design rather than coupling the two issues?

**Comment by Leonardo2718** [comment] 2020-03-19 14:27
I think making the destructor `noexcept(false)` will resolve the immediate problem, but it's not clear to me yet whether it will cause other problems (making destructors `noexcept(false)` generally does).

**Comment by Leonardo2718** [comment] 2020-04-13 19:59
I've spent some time thinking about this problem and I have a few solutions. I will use https://github.com/eclipse/omr/blob/6138048d2e6d431fa4e4a4c96ee7631627547a7b/compiler/x/amd64/codegen/OMRTreeEvaluator.cpp#L425-L431 as an example to illustrate the different possible solutions.

### 1. Using an explicit `end` call

I've been told an approach similar to this was the source of several bugs at one point.  However, it is a pretty "standard" solution so I'm including it anyways for the purpose of discussion.

```c++
{ 
TR_OutlinedInstructionsGenerator og(slowPathLabel, node, cg); 
generateRegImm64Instruction(MOV8RegImm64, node, treg, DOUBLE_NAN, cg); 
generateLabelInstruction(JMP4, node, endLabel, cg);
og.end();
} 
```

An assert can be added to `TR_OutlinedInstructionsGenerator`s destructor to make sure `end()` is invoked before the object goes out of scope (asserts in destructors are usually ok if they are guaranteed to abort the program when triggered).

### 2. Using a macro to wrap the outlined instruction generation

Here, the setup and cleanup is done by a macro that wraps the code that actually injects the outlined instructions.

```c++
/* NOTE: the real thing would have to be a lot smarter */
#define DEFINE_OUTLINED_INSTRUCTIONS(_entryLabel, _node, _cg, f) \
   do { \
   auto _oi = new (cg->trHeapMemory()) TR_OutlinedInstructions(_entryLabel, _cg); \
   _oi->setCallNode(node); \
   cg->getOutlinedInstructionsList().push_front(_oi); \
   _oi->swapInstructionListsWithCompilation(); \
   generateLabelInstruction(LABEL, _node, _entryLabel, _cg); \
        \     
   {f}  \
        \
   generateLabelInstruction(LABEL, _oi->_callNode, generateLabelSymbol(_cg), _cg); \
   _oi->swapInstructionListsWithCompilation(); \
   } while (0)

/* ... */

DEFINE_OUTLINED_INSTRUCTIONS(slowPathLabel, node, cg, {
   generateRegImm64Instruction(MOV8RegImm64, node, treg, DOUBLE_NAN, cg);
   generateLabelInstruction(JMP4, node, endLabel, cg);
   });
```

I'm not a fan of this solution because the macro definition is quite ugly, IMO.

### 3. If we had C++11 lambdas

I'm including this solution because I think it is rather elegant but it requires C++11 lambdas.

It is similar to the previous solution. But, instead of putting the setup/cleanup code in a macro, it goes in a high-order function that another function as argument that actually does the instruction generation when called. So, the instruction generation can be simply wrapped in a lambda when the high-order function is invoked.

```c++
template <typename F>
void
defineOutlinedInstructions(TR::LabelSymbol* entryLabel, TR::Node* node, TR::CodeGenerator* cg, F f)
   {
   auto _oi = new (cg->trHeapMemory()) TR_OutlinedInstructions(entryLabel, cg);
   _oi->setCallNode(node);
   cg->getOutlinedInstructionsList().push_front(_oi);
   _oi->swapInstructionListsWithCompilation();
   generateLabelInstruction(LABEL, node, entryLabel, cg);

   f();

   generateLabelInstruction(LABEL, _oi->_callNode, generateLabelSymbol(_oi->_cg), _oi->_cg);
   _oi->swapInstructionListsWithCompilation();
   }

/* ... */

self()->defineOutlinedInstructions(slowPathLabel, node, cg, [](){
   generateRegImm64Instruction(MOV8RegImm64, node, treg, DOUBLE_NAN, cg);
   generateLabelInstruction(JMP4, node, endLabel, cg);
   });
```

**Comment by andrewcraik** [comment] 2020-05-11 17:54
Ok so this has been sitting for too long and we need to make some kind of progress on it. If marking the destructor isn't a suitable workaround until we get C++11 support then I would say the function macro is the solution to adopt until C++11 support is available. Ideally, if we have the support we might def the macro to the lamda... 

Does that seem reasonable @Leonardo2718 ?

**Comment by andrewcraik** [comment] 2020-05-12 14:05
So there has been some additional offline discussion. Option 1 is quick to implement, 2 will take more time and 3 is where we would like to go once the build compilers work. Given this I think if someone can get option 1 done for now with an appropriate assert to guard against the mis-matched calls problem that is the best tactical fix and we can get option 2 implemented at a more leisurely pace one people are no longer being affected by the bug. FYI @Leonardo2718 and @dsouzai based on our discussions. Thank you for your contributions to helping formulate a plan to tackle this tricky issue.

**Comment by Leonardo2718** [comment] 2020-05-12 17:24
I agree that's a reasonable plan. I will work on implementing option 1 then.

**Comment by Leonardo2718** [comment] 2020-05-12 19:51
Bellow, I've broken down the steps to implement option 1 as a tactical fix. I will update the status of each item as the work progresses.

- [ ] In OMR, add an empty definition of `TR_OutlinedInstructionsGenerator::endOutlinedInstructionSequence()`
- [ ] In OpenJ9, add calls to `endOutlinedInstructionSequence()` in all the places that need it
- [ ] In OMR
  - [ ] add calls to `endOutlinedInstructionSequence()` in all the places that need it
  - [ ] move the clean up code from  `~TR_OutlinedInstructionsGenerator()`

**Closed** 2020-05-22 20:55 UTC
Labels: arch:x86, bug, comp:compiler
