### ISSUE TITLE
Does porttest really run?

### ISSUE THREAD

**Issue by mstoodle** [eclipse/omr#6299] opened 2022-01-13 15:36 UTC
I found myself digging through the full console output for a test run on linux x86 and discovered:
```
21:11:14  test 31
21:11:14        Start 31: porttest
21:11:14  
21:11:14  31: Test command: /home/jenkins/workspace/Build/build/fvtest/porttest/omrporttest "--gtest_output=xml:/home/jenkins/workspace/Build/build/fvtest/porttest/omrporttest-results.xml" "--gtest_filter="
21:11:14  31: Test timeout computed to be: 9.99988e+06
21:11:14  31: Note: Google Test filter = 
21:11:14  31: [==========] Running 0 tests from 0 test cases.
21:11:14  31: [==========] 0 tests from 0 test cases ran. (1 ms total)
21:11:14  31: [  PASSED  ] 0 tests.
21:11:14  31: [  ALL TESTS PASSED  ] 
```

That doesn't seem right to me, but maybe I'm missing something.

**Comment by davidjmccann** [comment] 2022-05-05 10:34
@babsingh Is this covered by #6487?

**Comment by babsingh** [comment] 2022-05-05 14:22
Yes, #6487 should cover this issue. This issue is a duplicate of https://github.com/eclipse/omr/issues/6486. Latest builds, e.g. https://ci.eclipse.org/omr/job/PullRequest-osx_x86-64/, will indicate that `porttest` is run correctly. Thus, closing this issue.

**Closed by babsingh** 2022-05-05 14:22 UTC
Labels: question, comp:port, comp:test
