### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by Spencer-Comin** [eclipse/omr#6866] opened 2023-01-17 19:50 UTC
The link "[Building Your Own Runtime](https://ibm.box.com/s/7xdg25we2ezmdjjbqdys30d7dl1iyo49)" shows me the file is removed or unavailable:
<img width="601" alt="image" src="https://user-images.githubusercontent.com/52704940/212996478-c6bf1621-7faf-4658-aab1-ae135880a872.png">

Both links in [Blog Posts about OMR technologies](https://github.com/eclipse/omr#blog-posts-about-omr-technologies) take me to an IBM page not found page:
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/52704940/212997056-eca238f7-2da5-4f19-b645-25ff15995ff0.png">

**Comment by hzongaro** [comment] 2023-03-06 16:11
I just noticed that this broken link was previously mentioned in issue #5588, so I will close this as a duplicate.

**Comment by hzongaro** [comment] 2023-03-06 16:12
Duplicate of #5588

**Closed** 2023-03-06 16:12 UTC
Labels: duplicate
