### ISSUE TITLE
Crash in Compiler testing on OSX

### ISSUE THREAD

**Issue by charliegracie** [eclipse/omr#468] opened 2016-11-10 20:37 UTC
The following #464 is failing in compiler tests on OSX which seem very unlikely related to the changes in the PR.  Is there someone more familiar with the compiler component who can talk a look @0xdaryl, @vijaysun-omr or @mstoodle?

Here is a link to the travis job which failed even on restart:
https://travis-ci.org/eclipse/omr/jobs/174819405

Here is the output from the failing test:
./structarray
Step 1: initialize JIT
Step 2: define type dictionary
Step 3: compile createMethod builder
Step 4: compile readMethod builder
Assertion failed at ../compiler/optimizer/GlobalRegisterAllocator.cpp:2829: 0
	couldn't find the global register
compiling src/StructArray.cpp:98:testReadStructArray at level: warm

Assertion failed: (0), function assumeDontCallMeDirectlyImpl, file ../compiler/infra/Assert.cpp, line 140.
make[2]: *** [test] Abort trap: 6 (core dumped)
make[1]: *** [omr_jitbuildertest] Error 2
make: *** [test] Error 2

**Comment by mstoodle** [comment] 2016-11-10 22:23
@Leonardo2718 could you please take a look at this one (since it's a test you just created :) ) and generate a log with traceGRA,traceFull with the error. Then @vijaysun-omr is probably the best one to review that log so we can get the problem addressed.

**Comment by Leonardo2718** [comment] 2016-11-11 15:58
I've been trying to investigate this issue but haven't been able to reproduce this particular failure. Instead, I've been getting intermittent segfaults, different assert failures (different from the one reported here), and runs that just work.

However, using valgrind (on my local Linux machine) has revealed a problem in this particular test case that's related to issue #406. Fixing the issue locally seems to have also resolved the behavior I was seeing on OSX.

I will submit a fix to the test case, noting that its a workaround for #406.

**Comment by mstoodle** [comment] 2016-11-14 16:01
Should be resolved via #484

**Closed by mstoodle** 2016-11-14 16:01 UTC
Labels: bug, compiler
