### ISSUE TITLE
Questions: About option  -Xjit:disableInlining

### ISSUE THREAD

**Issue by yongqinglu** [eclipse/omr#4874] opened 2020-02-28 10:33 UTC
When to run a J9 program with the option  -Xjit:disableInlining, we got call stacks including some functions which names include the words "Inline" as follows. Does it make sense when to be with -Xjit:disableInlining? Thank you very much.

estimateAndRefineBytecodeSize__16TR_J9InlinerUtilFP11TR_CallSiteP13TR_CallTargetP12TR_CallStackRi
applyPolicyToTargets__14TR_InlinerBaseFP12TR_CallStackP11TR_CallSite
**getSymbolAndFindInlineTargets**__14TR_InlinerBaseFP12TR_CallStackP11TR_CallSiteb
**inlineCallTargets**__28TR_MultipleCallTargetInlinerFPQ2_2TR20ResolvedMethodSymbolP12TR_CallStackP24TR_InnerPreexistenceInfo
**performInlining**__14TR_InlinerBaseFPQ2_2TR20ResolvedMethodSymbolperform__10TR_InlinerFv
performOptimization__Q2_3OMR9OptimizerFPC20OptimizationStrategyiN22
optimize__Q2_3OMR9OptimizerFv
compile__Q2_3OMR11CompilationFv

**Comment by Leonardo2718** [comment] 2020-02-28 14:21
I think this question would be better located in [OpenJ9](https://github.com/eclipse/omr)? That said, @andrewcraik might have an answer for you.

**Comment by fjeremic** [comment] 2020-02-28 14:55
Tagging @cathyzhyi as our inliner expert as well.

**Comment by cathyzhyi** [comment] 2020-02-28 16:19
-Xjit:disableinlining should disable the `inlining optimization`. 
"inlining" sometimes can still happen with -Xjit:disableinlining because `TR_InlineCall` which is not a stand-alone optimization but a tool to do inlining can be used by other optimizations like ValuePropagation and EscapeAnalysis https://github.com/eclipse/omr/blob/250665b8ad62de18b019bb29cb5531fa097227a6/compiler/optimizer/Inliner.hpp#L441
However, it seems even the inlining optimization is not correctly disabled based on the backtrace pasted here which is weird.
@yongqinglu Could you provide more details on how the program is running? how are you setting the Java option? do you use an environment variable? Is there only one JVM involved? Thanks!

**Comment by yongqinglu** [comment] 2020-03-02 07:18
@cathyzhyi  Thanks for looking at the issue. We can get the javacore file of the jvm in which there is the option:
2CIUSERARG               -Xjit:disableInlining
So, seems the option is set already.
The running java command is like: 
java ... ... -Xms512m -Xnoclassgc -Xmx1534m -Xminf0.3 -Xmaxf0.6 **-Xjit:disableInlining** -Xjit:exclude={org/apache/log4j/*} ... ... org.apache.catalina.startup.Bootstrap start
The version of the java is pap3280sr5fp40-20190807_01(SR5 FP40)

**Comment by cathyzhyi** [comment] 2020-03-02 17:04
@yongqinglu I think the problem is that the second `-Xjit` overwrites the first one. You can put the 2 options together like `-Xjit:exclude={org/apache/log4j/*},disableInlining`

**Comment by yongqinglu** [comment] 2020-03-03 06:04
@cathyzhyi Thanks, Will suggest customer to apply it.

**Comment by 0xdaryl** [comment] 2021-02-01 22:02
Issue seems to be resolved.  Closing.

**Closed by 0xdaryl** 2021-02-01 22:02 UTC
Labels: question
