### ISSUE TITLE
ludiv with two constant children is not being simplified

### ISSUE THREAD

**Issue by Leonardo2718** [eclipse/omr#2218] opened 2018-01-13 00:24 UTC
When compiling the following Tril method:

```
(method return=Int64 
  (block
    (lureturn
      (ludiv
        (luconst 1) 
        (luconst 18446744073709551615)) )))
```

the expectation is that the IL will be simplified to:

```
ureturn
  luconst 0
```

This, however, does not happen. Instead, the code generator is given the un-simplified IL which it then handles incorrectly. On an AMD64 Linux machine the generated code for the above method is:

```asm
mov eax, 0x00000001
sar rax, 0x00
neg rax
ret
```

which returns 18446744073709551615 instead of 0 when executed.

It should be noted that the "simpler" case:

```
lureturn
  ludiv
    luconst 1
    luconst 42
```

*is* simplified correctly.

**Comment by 0xdaryl** [comment] 2018-01-13 15:21
The problem is that the division-by-constant strength reduction algorithm for signed values does not work for arbitrary unsigned divisors.  In the x86 code generator, there is no attempt made to guard (or limit) that optimization for unsigned arithmetic.  The immediate fix for this problem is to add that check (I can provide this); the longer term fix is to apply an unsigned algorithm when applicable (and make sure unsigned division is handled consistently across all code generators).

The Power code generator does not support 64-bit unsigned division at all (it asserts).  For 32-bit, I believe it allows the signed strength reduction to occur with unsigned values for a range of divisors that will provably still work.  Otherwise, it falls back to a general 32-bit unsigned division.

The Z code generator handles 32-bit and 64-bit unsigned division.  For unsigned division by a constant, it only handles special cases (like division by 1 or by a power of 2) before it falls back to the general implementation.

Unsigned long division on ARM is not implemented.

**Closed** 2018-01-15 18:38 UTC
Labels: bug, compiler
